### ISSUE TITLE
Ask for technique report

### ISSUE THREAD

**Issue by Xiangyu-CAS** [vimar-gu/Bias-Eliminate-DA-ReID#2]
At first, congrats to you for good result in VisDA challenge.
 
Could you provide link for your technique report? Thanks.

BTW, I am curious about your result on validation set. My single model submission hits 79% mAP and 89% rank1 on validation set, but according to READ.md, your result is much lower.  Is it a complete form ?

**Comment by vimar-gu** [comment]
We want to release the technique report after the final results is announced. 
For the second question, we are also reproducing our results. There may be some updates afterwards. Besides, the results are produced with model-predicted camera labels and offline. If the ground truth camera labels are used, the results will be much better, similar to your results. And as the online validation server is off now, we reproduced the results based on our offline code, which brought lower mAP.

**Comment by Xiangyu-CAS** [comment]
Thank you for reply ： ）
