### ISSUE TITLE
Step3: Train domain adaptation.

### ISSUE THREAD

**Issue by Simon4Yan** [vimar-gu/Bias-Eliminate-DA-ReID#3]
Hi, 

I go to step 3 :
`python train_adaptation.py --config=configs/adaptation.yml
`
What is the _CAMERA_WEIGHT: "the/path/to/your/camera/model"_ in adaptation.yml ?

I met: `[Errno 2] No such file or directory: 'the/path/to/your/camera/model'`

Then, I run Step 4, I met:

```
Traceback (most recent call last):
  File "train_camera.py", line 98, in <module>
    main()
  File "train_camera.py", line 95, in main
    train(cfg)
  File "train_camera.py", line 52, in train
    model.load_param(cfg.MODEL.PRETRAIN_PATH,cfg.MODEL.PRETRAIN_CHOICE)
  File "Bias-Eliminate-DA-ReID/modeling/baseline.py", line 397, in load_param
    self.state_dict()[i].copy_(param_dict[i])
KeyError: 'state_dict'
```
Any idea to solve it? Thanks!

**Comment by Simon4Yan** [comment]
https://github.com/vimar-gu/Bias-Eliminate-DA-ReID/blob/2f9b022d00bbcb6e74d4cd0c3f40c9bcd5603135/configs/camera.yml#L2

The "camera" might be "imagenet"?

**Comment by vimar-gu** [comment]
Oh yes I'm sorry. The adaptation stage doesn't need the camera model but it is asked in the code. So the camera model should be trained before adaptation stage. 
And the "camera" option is due to training the camera model with baseline model. So actually there is no need to be this "camera" option. 
I will fix these bugs asap.

**Comment by vimar-gu** [comment]
And actually there're some mistakes in the config setting on the finetune option and clustering distance threshold parameter. So I'll correct it as well. 
Sorry to cause these troubles to you.

**Comment by Simon4Yan** [comment]
Hi, thanks for your reply. It's okay regarding this issue. I just want to make sure the codes can be run smoothly, and it is understandable if there are some small code issues (which are irrelevant with method, just coding faults).

I will run again, thanks!
