### ISSUE TITLE
 I want to read the technical report

### ISSUE THREAD

**Issue by yyang-2018** [vimar-gu/Bias-Eliminate-DA-ReID#5]
Hello,I'd like to ask where can I read the Technical Report about your work ? This link is  invalid.
https://github.com/Simon4Yan/VisDA2020_Code_From_Top_Teams/blob/master/Technical_reports/vimar.pdf 
I look forward to your reply,thank you!

**Comment by vimar-gu** [comment]
Hi, we have uploaded the technique report now. You can check it out from [https://github.com/vimar-gu/Bias-Eliminate-DA-ReID/blob/master/files/TechReport.pdf](https://github.com/vimar-gu/Bias-Eliminate-DA-ReID/blob/master/files/TechReport.pdf).
Thanks for you remind~

**Comment by yyang-2018** [comment]
Thank you for your reply.Now I can read it.
