### ISSUE TITLE
SPGAN-transferred dataset

### ISSUE THREAD

**Issue by want2knoww** [vimar-gu/Bias-Eliminate-DA-ReID#6]
First, I would like to thank you for sharing the code of your awesome projects. I am trying to run your code and reproduce your results. However, I can't find the SPGAN-transfered dataset. Could you share the download link to the dataset you used?

**Comment by vimar-gu** [comment]
I'm sorry that due to the limitation of data privacy, we are not allowed to provide the corresponding data. 
> https://github.com/vimar-gu/Bias-Eliminate-DA-ReID/issues/4#issue-686145567

The real images in this challenge is part of Market-1501. You can run SPGAN with Market-1501 and PersonX to obtain similar transferred dataset.
