### ISSUE TITLE
使用duke数据集进行测试时参数设置的问题

### ISSUE THREAD

**Issue by want2knoww** [vimar-gu/Bias-Eliminate-DA-ReID#8]
您好，我最近正在使用您的代码对duke数据集进行测试。但在对数据集读取的参数设置中遇到了困难。

duke数据集中文件名的格式为如 0073_c1_f0064877.jpg，
但在visda_datasrt.py文件中的代码为
def _process_dir(self, dir_path, relabel=False):
        if dir_path == '':
            return []

        img_paths = sorted(glob.glob(osp.join(dir_path, '*.png')) + glob.glob(osp.join(dir_path, '*.jpg')))
        pattern = re.compile(r'([\d]+)_([\d]+)_([\d]+)')

        pid_container = set()
        for img_path in img_paths:
            pid, _, _ = map(int, pattern.search(img_path).groups())
            if pid == -1: continue  # junk images are just ignored
            pid_container.add(pid)
        pid2label = {pid: label for label, pid in enumerate(pid_container)}

        dataset = []
        for i in range(len(img_paths)):
            img_path = img_paths[i]
            pid, camid, pidx = map(int, pattern.search(img_path).groups())
            if pid == -1: continue  # junk images are just ignored
            if relabel: pid = pid2label[pid]
            dataset.append((img_path, pid, camid, self.setid, i, pidx))

        return dataset, pid2label

请问我应该如何设置代码以读取pidx呢？

**Comment by vimar-gu** [comment]
可以参照
> https://github.com/michuanhaohao/reid-strong-baseline/blob/3da7e6f03164a92e696cb6da059b1cd771b0346d/data/datasets/dukemtmcreid.py#L89

进行数据集代码的修改
